#!/bin/bash
x=$(acpi | grep -E -o [0-9][0-9]% | grep -o [0-9][0-9] )
if [ $x -le 7 ] ; then
  notify-send "Battery is low $x% 😌 "
fi
: '
  This is added to a cron and called every 5 minutes
  crontab -e
  */5 * * * * /path/to/some-script.sh
'
