#!/bin/bash
x=$(acpi | grep -E -o [0-9]?[0-9]% | grep -E -o [0-9]?[0-9])
if [ $x -le 7 ] ; then
   XDG_RUNTIME_DIR=/run/user/$(id -u) /usr/bin/notify-send "😌 Battery is low $x% 😌 "
fi
: '
  This is added crontab, called every 5 minutes:
  $ crontab -e
  " */5 * * * * /path/to/some-script.sh "
'
